spring:
  datasource:
    url: ${CORE_DB_URL}
    username: ${CORE_DB_USERNAME}
    password: ${CORE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create #update로 바꿀것
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: trace

# Solapi SMS 설정
solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  sender: ${SOLAPI_SENDER_NUMBER}