# workflow name
name: CD Pipeline

on:
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug TAG
        run: echo "TAG=${{ github.event.client_payload.tag }}"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        env:
          TAG: ${{ github.event.client_payload.tag }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/deploy

            docker pull geooeg/jjubul-resource:${TAG}

            LIVE_PORT=$(grep -o "808[0-1]" /etc/nginx/conf.d/jjubul.conf)
            
            if [ "$LIVE_PORT" = "8080" ]; then
              TARGET_COMPOSE="docker-compose.green.yml"
              TARGET_PORT=8081
            else
              TARGET_COMPOSE="docker-compose.blue.yml"
              TARGET_PORT=8080
            fi
            
            sed -i "s|image: geooeg/jjubul-resource:.*|image: geooeg/jjubul-resource:${TAG}|g" $TARGET_COMPOSE
            
            docker-compose -f $TARGET_COMPOSE down
            docker-compose -f $TARGET_COMPOSE up -d

            sudo sed -i "s|proxy_pass http://localhost:808[0-1]|proxy_pass http://localhost:${TARGET_PORT}|g" /etc/nginx/conf.d/jjubul.conf
            sudo nginx -s reload
