# workflow name
name: CD Pipeline

# 트리거
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Read image tag
        run: echo "TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/deploy

            # 최신 이미지 pull
            docker pull geooeg/jjubul-resource:${TAG}

            # 현재 nginx 라우팅 포트번호 확인 (e.g 8080, 8081)
            LIVE_PORT=$(grep -o "808[0-1]" /etc/nginx/conf.d/jjubul.conf)
            
            # 8080이면 blue가 돌아가고 있음, green에 배포
            if [ "$LIVE_PORT" = "8080" ]; then
              TARGET_COMPOSE="docker-compose.green.yml"
              TARGET_PORT=8081
            
            # 8081이면 green이 돌아가고 있음, blue에 배포
            else
              TARGET_COMPOSE="docker-compose.blue.yml"
              TARGET_PORT=8080
            fi
            
            # compose 내부 이미지 태그 자동 교체
            sed -i "s|image: geooeg/jjubul-resource:[0-9\.]*|image: geooeg/jjubul-resource:${TAG}|g" $TARGET_COMPOSE

            # blue 서버 재배포
            docker-compose -f $TARGET_COMPOSE down
            docker-compose -f $TARGET_COMPOSE up -d

            # nginx 전환
            sudo sed -i "s|proxy_pass http://localhost:808[0-1];|proxy_pass http://localhost:$TARGET_PORT;|g" /etc/nginx/conf.d/jjubul.conf
            sudo nginx -t
            sudo nginx -s reload
